spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time_deposits
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

api:
  base-path: /api/v1

logging:
  level:
    org.ikigaidigital: DEBUG
